### ISSUE TITLE
doctests try to link multiple identical dependency on the same path

### ISSUE THREAD

**Issue by sorpaas** [rust-lang/cargo#5658]
I think this is a regression. This works on rustc/cargo 1.26 but fails on rustc/cargo 1.27.

We have a dependency in the project `parity-dapps-glue`. This crate is published in crates.io, and we have a crate (`parity-dapps`) depending on the crates.io version. There's another local version of `parity-dapps-glue`. That local version is not being dependent by any other crates in the project, but it's included as a member of the workspace.

Given we have a checkout of parity:

```
git clone https://github.com/paritytech/parity
cd parity
git checkout 683a26c8300c7022950bb2d678b82a616b79d434
```

Go to the `parity-dapps-glue` folder and run `cd dapps/js-glue && cargo test --release --verbose` works without any issue. However, when in the root folder of the project, run command `cargo test --all --release --verbose` fails with the following error:

```
error[E0465]: multiple rlib candidates for `syntex` found
  --> /home/sorpaas/repos/parity3/dapps/js-glue/src/lib.rs:21:1
   |
21 | extern crate syntex;
   | ^^^^^^^^^^^^^^^^^^^^
   |
```

Checking the command cargo tries to run:

```
   Doc-tests parity-dapps-glue
     Running `rustdoc --test /home/sorpaas/repos/parity3/dapps/js-glue/src/lib.rs --crate-name parity_dapps_glue -L dependency=/home/sorpaas/repos/parity3/target/release/deps -L native=/home/sorpaas/repos/parity3/target/release/build/backtrace-sys-e4eacff605b4f055/out/.libs -L native=/home/sorpaas/repos/parity3/target/release/build/eth-secp256k1-0b8b502d1bbb696e/out -L native=/home/sorpaas/repos/parity3/target/release/build/hidapi-a9e9c4be500acaed/out -L native=/home/sorpaas/repos/parity3/target/release/build/libusb-sys-5da7ff895ff6110a/out -L native=/home/sorpaas/repos/parity3/target/release/build/ring-a01f8d7f275bc597/out -L native=/home/sorpaas/repos/parity3/target/release/build/rocksdb-sys-0cc50aca43312c87/out -L native=/home/sorpaas/repos/parity3/target/release/build/rust-crypto-55bc03d3db1ecfb2/out -L native=/home/sorpaas/repos/parity3/target/release/build/snappy-sys-d06997f537a1bcfc/out -L dependency=/home/sorpaas/repos/parity3/target/release/deps --cfg 'feature="with-syntex"' --cfg 'feature="syntex"' --cfg 'feature="default"' --cfg 'feature="quasi"' --cfg 'feature="quasi_codegen"' --cfg 'feature="syntex_syntax"' --extern glob=/home/sorpaas/repos/parity3/target/release/deps/libglob-a2dd3ee8473024ce.rlib --extern glob=/home/sorpaas/repos/parity3/target/release/deps/libglob-f0c88b0834dadf39.rlib --extern mime_guess=/home/sorpaas/repos/parity3/target/release/deps/libmime_guess-82ea2dbb34000842.rlib --extern aster=/home/sorpaas/repos/parity3/target/release/deps/libaster-698a2daf00391c43.rlib --extern mime_guess=/home/sorpaas/repos/parity3/target/release/deps/libmime_guess-aa77cd54b7d2d450.rlib --extern aster=/home/sorpaas/repos/parity3/target/release/deps/libaster-79f91cd1dc587a34.rlib --extern syntex=/home/sorpaas/repos/parity3/target/release/deps/libsyntex-abd568c68cb25604.rlib --extern parity_dapps_glue=/home/sorpaas/repos/parity3/target/release/deps/libparity_dapps_glue-20efa3d1d1c05826.rlib --extern syntex_syntax=/home/sorpaas/repos/parity3/target/release/deps/libsyntex_syntax-fb8bb9b97a7fa6c4.rlib --extern syntex=/home/sorpaas/repos/parity3/target/release/deps/libsyntex-223e04c9da4376ef.rlib --extern quasi=/home/sorpaas/repos/parity3/target/release/deps/libquasi-638391ea1d3064e7.rlib --extern syntex_syntax=/home/sorpaas/repos/parity3/target/release/deps/libsyntex_syntax-eaa12227fbcdf6de.rlib --extern quasi=/home/sorpaas/repos/parity3/target/release/deps/libquasi-6bf50ce5ae2c2f13.rlib`
```

You can see there're two `--extern syntex` arguments pointing to different files.

I checked the doctests build for `cd dapps/js-glue && cargo test --release --verbose` and `cargo test --release --all --verbose`, they're building with the same feature sets.

* I expected to see this happen: The above command works just as in rust/cargo 1.26.
* Instead, this happened: It fails with error.
* `rustc` version: `rustc 1.27.0 (3eda71b00 2018-06-19)`
* `cargo` version: `cargo 1.27.0 (1e95190e5 2018-05-27)`

rel https://github.com/paritytech/parity/pull/8983

**Comment by ehuss** [comment]
Thanks @sorpaas for the report.  I have a fix for this in #5651.

**Comment by ehuss** [comment]
@sorpaas, if you're able, can you test with the latest nightly?  It should be fixed now.

**Comment by sorpaas** [comment]
Going to try with the previous commit tomorrow.

**Comment by ehuss** [comment]
Going to close this for now.  @sorpaas if you find any issues, please let me know.
