### PR TITLE
Implement renaming dependencies in the manifest

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit implements a new unstable feature for manifests which allows
renaming a crate when depending on it. For example you can do:

```toml
cargo-features = ["dependencies-as"]

...

[dependencies]
foo = "0.1"
bar = { version = "0.1", registry = "custom", package = "foo" }
baz = { git = "https://github.com/foo/bar", package = "foo" }
```

Here three crates will be imported but they'll be made available to the Rust
source code via the names `foo` (crates.io), `bar` (the custom registry), and
`baz` (the git dependency). The *package* name, however, will be `foo` for all
of them. In other words the git repository here would be searched for a crate
called `foo`. For example:

```rust
extern crate foo; // crates.io
extern crate bar; // registry `custom`
extern crate baz; // git repository
```

The intention here is to enable a few use cases:

* Enable depending on the same named crate from different registries
* Allow depending on multiple versions of a crate from one registry
* Removing the need for `extern crate foo as bar` syntactically in Rust source

Currently I don't think we're ready to stabilize this so it's just a nightly
feature, but I'm hoping we can continue to iterate on it!

cc #1311

### CODE REVIEW

**Comment by sfackler** [comment]
This may have already been discussed elsewhere, but I think it would be a bit less confusing to do something like this:

```toml
[dependencies]
foo = "0.1"
bar = { version = "0.1", registry = "custom", name = "foo" }
baz = { git = "https://github.com/foo/bar", name = "foo" }
```

It avoids the extra array, and makes it so that the set of names you're importing (modulo crate/lib naming differences) are all in the same place.

**Comment by alexcrichton** [comment]
Heh that's actually the first syntax I thought of as well, although it was changed due to https://github.com/rust-lang/rfcs/pull/2126#issuecomment-328921126, namely:

> the desired crate alias as the leading key in Cargo.toml conflates packages and crates (a common conflation that we should probably work on separately).

For example today you actually specify *package* names as the key in `[dependencies]` whereas the `as`/alias business we want is to rename the crate. (it's possible for packages to be named differently from their library crate).

That being said I also just realized something that can be troubling. How, for example, do we enable features for these dependencies? For example:

```toml
[dependencies]
foo = [
   { version = "0.1" },
   { version = "0.1", registry = "custom", as = "bar" },
   { git = 'https://github.com/foo/bar, as = "baz" },
]

[features]
some-feature = ["foo/another-feature"] # what version of `foo`?
```

This I think is much clearer with what @sfackler is thinking:

```toml
[dependencies]
foo = "0.1"
bar = { version = "0.1", registry = "custom", name = "foo" }
baz = { git = "https://github.com/foo/bar", name = "foo" }

[features]
some-feature = ["foo/another-feature"] # aha, the crates.io version!
```

That may tip my own opinion towards the latter!

**Comment by sfackler** [comment]
Oh yeah, good point. It's too bad you're allowed to set the library name separately from the crate name :(

File: src/cargo/core/features.rs [hunk 1]
```diff
@@ -125,6 +125,9 @@ features! {
 
         // Downloading packages from alternative registry indexes.
         [unstable] alternative_registries: bool,
+
+        // Downloading packages from alternative registry indexes.
```
Comment (matklad) [inline src/cargo/core/features.rs]: Wrong comment

File: src/cargo/ops/cargo_rustc/mod.rs [hunk 2]
```diff
@@ -931,28 +931,44 @@ Cargo.toml. This warning might turn into a hard error in the future.",
...
+            //
+            // This I believe mostly works out for now, but we'll likely want
+            // to tighten up this in the future.
+            let name = current.pkg.dependencies()
+                .iter()
+                .filter(|d| d.matches_ignoring_source(dep.pkg.summary()))
+                .filter_map(|d| d.rename())
+                .next();
+
+            v.push(name.unwrap_or(&dep.target.crate_name()));
```
Comment (matklad) [inline src/cargo/ops/cargo_rustc/mod.rs]: Could we make this `.unwrap_or` an utility method of something? Like `fn crate_name(&self) -> String`, which deals with `as` and, probably, with translating `-` to `_` as well.

File: tests/rename-deps.rs [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+            [project]
+            name = "foo"
+            version = "0.0.1"
+            authors = []
+
+            [dependencies]
+            bar = [
+                { version = "0.1.0" },
+                { version = "0.2.0", as = "baz" },
+            ]
```
Comment (matklad) [inline tests/rename-deps.rs]: Hm the syntax does not look too natural to me. Is the following a valid TOML?

```TOML
[dependencies]
bar = "0.1.0"
bar = { version = "0.2.0", as = "baz"}
```

Comment (alexcrichton) [reply tests/rename-deps.rs]: Unfortunately TOML-the-spec doesn't allow for something like that b/c it's counted as a redefinition of an existing key :(

**Comment by retep998** [comment]
If we wanted to make it clear where we're specifying the package name vs the crate name, perhaps we could do something like...
```toml
[dependencies]
foo = "0.1"
bar = { version = "0.1", registry = "custom", package = "foo" }
baz = { git = "https://github.com/foo/bar", package = "foo" }

[features]
some-feature = ["foo/another-feature"] # aha, the crates.io version!
```

**Comment by alexreg** [comment]
@alexcrichton Great work on this. I think this feature is very much due. Funnily enough, I was just going to suggest the key `package` (or `pkg`), but @retep998 just beat me to it. The semantics would be changed from your original approach, and the current method, with keys now representing user-facing crate names rather than package names, but it would at least be operationally backwards-compatible (in the case of no `package` value, that is). In other words, the value of the `package` field would default to the user-facing crate name (i.e. alias). This seems quite nice to me.

It's also worth noting that this PR helps with https://github.com/rust-lang/rust/issues/44660.

Finally, maybe add a "fixes https://github.com/rust-lang/cargo/issues/1311" to your original PR message?

**Comment by alexcrichton** [comment]
I've updated with the feedback so far (and switched to the non-array syntax using a `package` key), re-r? @matklad 


@alexreg oh we typically like to keep the issues open to track the feature, but I should have cc'd it in the original message for sure!

**Comment by alexreg** [comment]
@alexcrichton Yeah, that's fair enough. Anyway, the new semantics are with the alias on the LHS of the `=`, right? (i.e. what I elaborated on above.)

**Comment by alexcrichton** [comment]
@alexreg, correct!

**Comment by alexreg** [comment]
Super. Hopefully @matklad can review soon and then we can get this merged.

**Comment by alexcrichton** [comment]
@matklad sure yeah, although for specifying one crate twice we're already pretty bad about that today unfortunately. For example something like:


```toml
[dependencies]
foo = "0.1"

[target.'cfg(unix)'.dependencies]
foo = "0.1"
```

is accepted and works, so I figure we can probably just let rustc sort it out if it's specified multiple times.

File: src/cargo/core/dependency.rs [hunk 4]
```diff
@@ -27,6 +27,7 @@ struct Inner {
     specified_req: bool,
     kind: Kind,
     only_match_name: bool,
+    rename: Option<String>,
```
[the remark this answers is not in the document]
Comment (alexcrichton) [reply src/cargo/core/dependency.rs]: Oh this is slightly different through b/c it's not actually the package, but rather what the dependency is renaming the crate to

[the remark this answers is not in the document]
Comment (alexreg) [reply src/cargo/core/dependency.rs]: Yeah, even though there's a one-to-one correspondence with the `package` attribute, `rename` probably makes more sense in code (perhaps with a comment?)... that's my thought, anyway.

**Comment by alexreg** [comment]
Good work with this @acrichto! Thanks. 👍🏻

**Comment by alexreg** [comment]
Good work with this @alexcrichton! Thanks. 👍🏻

**Comment by peterjoel** [comment]
@matklad wrote:
>Using exactly the same library twice. This presumably should be an error


Probably should be a warning - and maybe not even that. Generated code shouldn't have to worry about this edge case. But two references to the same exact create should only result in the crate being included once, just with two aliases.

**Comment by aaronsky** [comment]
With this merged, does this mean that the item under #44931 should be updated? Apologies if this is the wrong place to ask about this

**Comment by alexreg** [comment]
@aaronsky Yep, it should be. Maybe ping @aturon on that thread to update the checkbox(es). :-)

**Comment by aldanor** [comment]
Here's a curious (but not so improbable) edge case with proc macros. Wondering how should this be handled? (or am I misunderstanding something)

- There's three crates, `foo`, `foo-derive` and `bar`
- `foo-derive` is a proc-macro crate which depends on crate `foo` (without any renaming) and mentions `::foo::Foo` in the resulting token stream
- `bar` is a top-level crate that depends on both `foo` and `foo-derive`
- Using the rename feature, in `bar`'s manifest we have `baz = { package = "foo" }`

Now the derive proc macro seems to be broken upon use, like so:

```rust
^^^^^^ Could not find `foo` in `{{root}}`
```

What would be a proper way to refer to it then?..

**Comment by aldanor** [comment]
Here's a concrete example, using [`num-derive`](https://github.com/rust-num/num-derive) as an example.

`Cargo.toml`:

```toml
cargo-features = ["rename-dependency"]

[package]
name = "rename-test"
version = "0.1.0"
edition = "2018"

[dependencies]
foo = { package = "num-traits", version = "0.2" }
num-derive = "0.2"
```

`src/lib.rs`:

```rust
use num_derive::{FromPrimitive, ToPrimitive};

#[derive(FromPrimitive, ToPrimitive)]
enum Color { Red, Blue, Green }
```

... which results in...

```
error[E0463]: can't find crate for `_num_traits`
 --> src/lib.rs:3:25
  |
3 | #[derive(FromPrimitive, ToPrimitive)]
  |                         ^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

**Comment by alexcrichton** [comment]
@aldanor that's a general problem with hygiene and procedural macros, and most procedural macros only work if the corresponding library crate is imported with one precise name (and not renamed). There's no way, for example, to get importing the `serde` crate under a different name to work with its derive modes.

**Comment by ehuss** [comment]
> maybe there should be some crate-resolving syntax

There is an issue open for this at rust-lang/rust#54363.

**Comment by updogliu** [comment]
Can this enable depending on the same version of a crate but using conflicting features at the same time (with different renaming of course)?

**Comment by ehuss** [comment]
@updogliu A package cannot have two dependencies to the same version of a crate.

**Comment by updogliu** [comment]
@ehuss What I am trying to achieve is using a crate of the same version but with conflicting features in two members of a workspace. Is that a valid motivation?

**Comment by ehuss** [comment]
If the two members are built separately, then they will each use a different copy of the dependent crate (with different features activated).  If the two members are being linked together, then it will unify the features and use a single copy.  Conflicting or mutually exclusive features aren't really supported.  There are a number of issues in the tracker here to make this more flexible, but we're still in the design phase.

**Comment by updogliu** [comment]
@ehuss I have an example at [here](https://github.com/updogliu/play/tree/master/ws_features). There are three members in a workspace: `foo`, `bar`, `common`. `foo` and `bar` do not depend on each other, but they both depend on `common` and using mutually exclusive features. Is this kind of use to be supported or not?

**Comment by retep998** [comment]
Mutually exclusive features are not supported.

**Comment by updogliu** [comment]
@retep998 I understand that it is currently not supported. But since this nice renaming dependencies feature is added to support using different versions of a crate, maybe it can be augmented a bit to support exclusive features under different renaming as well?

**Comment by updogliu** [comment]
Oh, there is already an example in the doc
https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section

**Comment by burdges** [comment]
I presume cargo features only work on nightly installs
