### ISSUE TITLE
Unexpected build failure with `feature-unification = "package"` mode

### ISSUE THREAD

**Issue by AMDmi3** [rust-lang/cargo#16529]
### Problem

As suggested in https://github.com/rust-lang/cargo/issues/14774#issuecomment-3750824795, I'm reporting unexpected build failure with (unstable) `feature-unification = "package"` mode (implemented in #15684 and tracked in #14774). I've come with simple crate hierarchy of two dependent crates, which build fine both at workspace level, and when each crate is built independently (or with `cargo hack --workspace build`), but fails to build with `feature-unification = "package"` mode.

Repro: https://github.com/AMDmi3/rust-feature-unification-bug-repro (build `cargo -Z feature-unification build` on nighly to reproduce).

### Steps

Try to build referenced repro workspace with `cargo -Z feature-unification build` on nighly.

### Version

```text
rustc 1.95.0-nightly (0a3cd3b6b 2026-01-18)
```

**Comment by epage** [comment]
```console
$ cargo tree --workspace --depth 2
a v0.1.0 (/home/epage/src/personal/dump/rust-feature-unification-bug-repro/a)
├── b v0.1.0 (/home/epage/src/personal/dump/rust-feature-unification-bug-repro/b)
│   └── sqlx v0.8.6
└── sqlx v0.8.6 (*)

b v0.1.0 (/home/epage/src/personal/dump/rust-feature-unification-bug-repro/b) (*)
```

Example error:
```
error[E0599]: the method `try_collect` exists for struct `Pin<Box<dyn Stream<Item = Result<O, Error>> + Send>>`, but i
ts trait bounds were not satisfied
     ╭▸ /home/epage/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sqlx-core-0.8.6/src/query.rs:438:30
     │
 438 │         self.fetch(executor).try_collect().await
     │                              ━━━━━━━━━━━ method cannot be called due to unsatisfied trait bounds
```

**Comment by aliu** [comment]
Decided to look into this (better late than never I guess). The important part of the error is actually here:
```
error[E0308]: mismatched types
  --> /home/andrew/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sqlx-core-0.8.6/src/any/connection/executor.rs:24:34
   |
17 |     ) -> BoxStream<'e, Result<Either<AnyQueryResult, AnyRow>, Error>>
   |          ------------------------------------------------------------ expected `Pin<Box<(dyn futures_core::Stream<Item = std::result::Result<either::Either<AnyQueryResult, AnyRow>, error::Error>> + std::marker::Send + 'e)>>` because of return type
...
24 |             Err(error) => return stream::once(future::ready(Err(error))).boxed(),
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected trait `futures_core::Stream`, found trait `futures_util::Stream`
   |
note: there are multiple different versions of crate `futures_core` in the dependency graph
  --> /home/andrew/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.34/src/stream.rs:37:1
   |
37 | pub trait Stream {
   | ---------------- this is the found trait
   |
  ::: /home/andrew/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.34/src/stream.rs:37:1
   |
37 | pub trait Stream {
   | ^^^^^^^^^^^^^^^^ this is the expected trait
   = help: you can use `cargo tree` to explore your dependency tree
```

It looks like some bug with how the package feature-unification is implemented which results in two `futures-core` crates with different feature sets being built together. Indeed if you look at the unit graph output you can see this (notice the different `index` values for `sqlx`):
```
> cargo build -Z feature-unification -Z unstable-options --unit-graph > graph.json
> jq ".units[.roots[0]]" graph.json
{
  "pkg_id": "path+file:///home/andrew/code/rust/rust-feature-unification-bug-repro/a#0.1.0",
...
  "dependencies": [
    {
      "index": 4,
      "extern_crate_name": "b",
      "public": false,
      "noprelude": false,
      "nounused": false
    },
    {
      "index": 122,
      "extern_crate_name": "sqlx",
      "public": false,
      "noprelude": false,
      "nounused": false
    }
  ]
}
> jq ".units[4]" graph.json
{
  "pkg_id": "path+file:///home/andrew/code/rust/rust-feature-unification-bug-repro/b#0.1.0",
...
  "dependencies": [
    {
      "index": 123,
      "extern_crate_name": "sqlx",
      "public": false,
      "noprelude": false,
      "nounused": false
    }
  ]
}
```

When building using package feature unification, the correct behavior would be to have 2 versions of `b`: the "top-level" one which is what you would get if you built `b` by itself, and the "dependency" one which is built when you build `a`. What seems to be happening is that when building the workspace, cargo is incorrectly combining the two `b`s and using the "top-level" `b` as the dependency of `a`, which results in two different `sqlx`s being linked (and transitively two different `futures-core`s).

I can try to fix this but I'm not familiar with how the package feature unification is implemented. @mladedav how difficult do you think this would be to fix?

**Comment by mladedav** [comment]
I have not seen the code for so long that I don't think I can give you any guess, sorry.
