### PR TITLE
Partially revert change to filter debug_assertions.

### LINKED ISSUE #7966: Regression in nightly handling features + debug assertions
**Problem**

`1.43.0-nightly (4ad624882 2020-03-03)` has regressed handling of debug assertions with features.

**Steps**
1. Install `1.43.0-nightly (4ad624882 2020-03-03)`

2. Build a crate with the following Cargo.toml

```
[package]
name = "test-bin"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket_contrib = { version = "0.4.2", features = [ "templates", "tera_templates" ] }
```

3. Build fails with:

```
   Compiling rocket_contrib v0.4.3
error[E0463]: can't find crate for `notify`
  --> /opt/rust/registry/src/crates-io-27bb2a0041c1489d/rocket_contrib-0.4.3/src/templates/fairing.rs:35:5
   |
35 |     extern crate notify;
   |     ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `rocket_contrib`.

To learn more, run the command again with --verbose.
```

Cargo has not downloaded the required crate, so I assume a Cargo bug, instead of a rustc bug.

4. Build works with `cargo 1.43.0-nightly (e57bd0299 2020-02-21)`

**Possible Solution(s)**

Dependency is pulled in via a debug assertion:

https://github.com/SergioBenitez/Rocket/blob/v0.4.2/contrib/lib/Cargo.toml#L79-L80

`notify` is not downloaded by Cargo during a clean build.

`Cargo.lock` does reference `notify`:

```
[[package]]
name = "rocket_contrib"
version = "0.4.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "66926894ef94396204c53885f54a1b0e94a88ce6c9478c2fd403261fc0efb523"
dependencies = [
 "glob 0.3.0",
 "log 0.4.8",
 "notify",
 "rocket",
 "serde",
 "serde_json",
 "tera",
]
```

This is a recent regression - `rust version 1.43.0-nightly (d3c79346a 2020-02-29)` also works.

Suspect https://github.com/rust-lang/cargo/pull/7962 is at fault,.

### PR DESCRIPTION
**Pull request by ehuss**
This partially reverts the changes from #7943. It caused a regression with the rocket_contrib crate. I knew that was the only crate that had a `cfg(debug_assertions)` dependency, and I saw that it had been fixed, but I did not realize the fix hadn't been published (and will be in a semver incompatible release).

This retains the old behavior for `cfg(debug_assertions)` of issuing a warning. I kept the filter for `CARGO_CFG_DEBUG_ASSERTIONS` for build scripts because that was the original intent for the change, and I don't see anyone using that.

Closes #7966.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

download error from crates.io
