### ISSUE TITLE
Nightly Cargo passes wrong rlib path for doctests

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/cargo#6954]
**Problem**

On the current nightly, with `rustc 1.36.0-nightly (7d5aa4332 2019-05-16)` and `cargo 1.36.0-nightly (c4fcfb725 2019-05-15)`, my [`build-plan`](https://github.com/jonas-schievink/build-plan) crate fails to compile doctests (of which there are none) during `cargo test`.

It fails while trying to build the crate for doctests, with this error:

```
   Doc-tests build-plan
error: extern location for serde does not exist: /home/jonas/dev/build-plan/target/debug/deps/libserde-270f7cf6cecf499d.rlib

error[E0463]: can't find crate for `serde`
  --> /home/jonas/dev/build-plan/src/lib.rs:14:1
   |
14 | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors
```

A failing CI build can be seen here: https://travis-ci.org/jonas-schievink/build-plan/builds/533879431?utm_medium=notification&utm_source=email

The cause of this must be something in the Cargo update PR https://github.com/rust-lang/rust/pull/60874, since it still works fine on the nightly before that (`cargo 1.36.0-nightly (759b6161a 2019-05-06)`)

**Steps**

1. `git clone https://github.com/jonas-schievink/build-plan.git`
2. `cd build-plan`
3. `cargo test`

**Possible Solution(s)**

**Notes**

Output of `cargo version`: cargo 1.36.0-nightly (c4fcfb725 2019-05-15)

**Comment by alexcrichton** [comment]
Thanks for the report! This looks specifically related to the integration test where `cargo build --build-plan` is deleting artifacts. I think this is caused by https://github.com/rust-lang/cargo/pull/6883 and is likely related to [this block](https://github.com/rust-lang/cargo/blob/c4fcfb725b4be00c72eb9cf30c7d8b095577c280/src/cargo/core/compiler/mod.rs#L286-L296), but `--build-plan` is an unstable option and candidate for breakage anyway.

**Comment by jonas-schievink** [comment]
Ah yes, that makes sense. I'm kind of surprised that a `--build-plan` invocation is deleting artifacts though.

**Comment by weihanglo** [comment]
Before closing, could we add a statement to the unstable doc `build-plan` for the deprecation, if we decide to?

**Comment by epage** [comment]
Closed by #16212
