### ISSUE TITLE
Undefined reference to __tsan_init when using thread sanitizer

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/cargo#10199]
### Problem

I am trying to use thread sanitizer in [my fork of triomphe](https://github.com/NobodyXu/triomphe) and it has link errors when trying to use thread sanitizer, complaining that a lot of symbols started with `__tsan_` is not found.

It used to work on 1.57 nightly, however upgrading it to 1.58 nightly causing it to fail.
It also failed when using 1.59 nightly.

Here is the [log](https://github.com/NobodyXu/triomphe/runs/4530192026?check_suite_focus=true) for the errors.

### Steps

1. `git clone https://github.com/NobodyXu/triomphe`
2. `RUSTFLAGS='-Zsanitizer=thread' cargo +nightly test -Z build-std --target --target $(uname -m)-unknown-linux-gnu  -- --nocapture`

### Version

```text
rustc 1.59.0-nightly (404c8471a 2021-12-14)
binary: rustc
commit-hash: 404c8471aba60c2d837fa728e7c729a0f52d5830
commit-date: 2021-12-14
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

**Comment by NobodyXu** [comment]
Similar things also happened in [my fork of arc-swap](https://github.com/NobodyXu/arc-swap/runs/4530422586?check_suite_focus=true), however this time it only happens in the github workflow.
