### ISSUE TITLE
Poor error message when multiple crates link the same native library

### ISSUE THREAD

**Issue by Ryman** [rust-lang/cargo#1006]
Example output from #886 

```
native library `openssl` is being linked to by more than one package, and can only be linked to by one package
  openssl-sys v0.0.1 (https://github.com/alexcrichton/openssl-sys#d66fe840)
  openssl-sys v0.0.1 (https://github.com/sfackler/rust-openssl#fa42ed9e)
```

In the issue linked above it was `hyper` and `curl-rust` with the dependency clash, but the message provided no information about that.

It would be an improvement if the output specified which crates caused each of the lines above, to save the user from delving into their lock file. Perhaps better again if the fix can be suggested (to depend on the same source in this case).

**Comment by eminence** [comment]
Is it possible to enhance these error messages to give some hints to the end-user about what to do?

**Comment by adals** [comment]
Updating registry `https://github.com/rust-lang/crates.io-index`
    Blocking waiting for file lock on the registry index
error: native library `sqlite3` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  libsqlite3-sys v0.4.0
  libsqlite3-sys v0.5.0


[dependencies]
nickel = "0.8.1"
nickel_sqlite = "*"
r2d2 = "*"
r2d2_sqlite = "*"

when change it to below it works
nickel = "0.8.1"
nickel_sqlite = "*"
r2d2 = "0.7"
r2d2_sqlite = "0.0.6"


extern crate r2d2;
#[macro_use] extern crate nickel;
extern crate nickel_sqlite;
extern crate r2d2_sqlite;

use r2d2::{Pool, Config};
use r2d2_sqlite::SqliteConnectionManager;
use nickel::{Nickel, HttpRouter};
use nickel_sqlite::{SqliteMiddleware, SqliteRequestExtensions};

#[derive(Debug)]
struct Person {
    id   : i32,
    name : String
}

const CREATE_TABLE : &'static str = "
  CREATE TABLE person (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL
  )";

fn main() {

    let mut app = Nickel::new();
    let db_url  = "file.db";
    let db_mgr  = SqliteConnectionManager::new(db_url.as_ref())
        .expect("Unable to connect to database");
    let db_pool = Pool::new(Config::default(), db_mgr)
        .expect("Unable to initialize connection pool");
    let db      = db_pool.clone().get().unwrap();

    match db.execute(CREATE_TABLE, &[]) {
        Ok(_)  => println!("created table 'person'"),
        Err(_) => {} // handle err
    };

    app.utilize(SqliteMiddleware::with_pool(db_pool));

    app.get("/persons/new/:name", middleware! { |req|
    let name = req.param("name").unwrap();
    let db = req.db_conn().unwrap();
    match db.execute("INSERT INTO person (name) VALUES ($1)", &[&name]) {
      Ok(_)    => format!("Sucessfully created an entry"),
      Err(err) => format!("Could not create a new entry: {}", err)
    }
  });

    app.get("/persons", middleware! { |request|
    let db = request.db_conn().unwrap();
    let mut stmt = db.prepare("SELECT id, name FROM person").unwrap();
    let person_iter = stmt.query_map(&[], |row| {
      Person{
        id   : row.get(0),
        name : row.get(1)
      }
    }).unwrap();
    let list = person_iter
        .map(|x| format!("<li>{}</li>", x.unwrap().name))
        .collect::<Vec<String>>()
        .concat();
    format!("<html><ul>{}</ul></html>", list)
  });

    app.listen("127.0.0.1:6767");
}

**Comment by atodorov** [comment]
Please provide some better error message. I'm seeing this on a project with tons of dependencies and I really have no idea which crates pull the different versions of libsqlite3-sys. Is there any way (command, options) for me to find out where the 2 versions come from ? I am happy to test a non-official build as well.

```
error: native library `sqlite3` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  libsqlite3-sys v0.8.0

  libsqlite3-sys v0.7.1
```

**Comment by fbruetting** [comment]
I had the same problem with diesel v0.11 & sqlite. For whatever reason, this was solved by compiling diesel v0.10 first, and then recompile with v0.11.

But this seems to not work properly, because after including `#[macro_use] extern crate diesel_codegen;` nothing works anymore due to:
```
error[E0468]: an `extern crate` loading macros must be at the crate root
 --> src/storage/mod.rs:3:1
  |
3 | extern crate diesel_codegen;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by lukaslueg** [comment]
Coming over here from #4459: It would be really helpful in this situation for cargo to give a hint on the dependency chains that cause this problem. Having had a very brief look at the code, one possibility may be to

* Make `Links::validate()` know about `Context`
* Add a walker to `util::Graph` that takes a `PackageID` and walks the first route it can find up the tree. This makes no guarantees towards efficiency or quality, yet we only need it in the error path and as long as this path remains, the problem remains.
* If a collision occurs, `Links::validate()` knows about both `PackageID`. Use the `Context.resolve`-graph to walk the dependency-tree from the offending packages up to the root.
* Print out an error message like

> error: more than one version of package `libsqlite3-sys` link to the native library `sqlite3`, but it can only be linked once.
> 
>   libsqlite3-sys v0.8.0 (dependency via foobar-0.4 < serde-derive-99 < barfoo-0.2 { git=".." } < [root]) links to `sqlite` 
>   libsqlite3-sys v0.7.1 (dependency via barfoo-0.1 < [root]) links to `sqlite`
> 
> Try updating or pinning your dependencies to ensure that this package only shows up once.

Any guides?
